### ISSUE TITLE
Refactor to easily add new handlers

### ISSUE THREAD

**Issue by runseb** [skippbox/kubewatch#23]
If someone wants to publish in IRC or telegram...etc.

We need a clean way to separate handlers and pass the handler config via command line option

**Comment by Gnouc** [comment]
@runseb Can you describe it more details?

Currently we have `--handler=<handler>` to specify which handler will be used.

What I understand with requirement of this issue is for dynamic loading handlers, isn't it?

**Comment by runseb** [comment]
What I mean is that we should structure the code to be more general.

- main should be be very generic and just read configuration settings

- pkg/ should have a list of handlers/ and a list of events/

**Comment by Gnouc** [comment]
@runseb Do you thing it's better to specify handler configuration through  configuration file and environment variables only, not command line arguments, something like:
```
handlers:
  slack:
    slack_token: xxx
    slack_channel: yyy
  irc:
    ...
  telegram:
    ...
```
