### ISSUE TITLE
can't access slack bahind corporate proxy

### ISSUE THREAD

**Issue by SydOps** [skippbox/kubewatch#58]
```
2016-12-19 05:55:45.587255 I | Post https://slack.com/api/chat.postMessage: dial tcp 54.192.xxx.xx:443: i/o timeout
```

There is a container named proxy, but I don't think it is for proxy access. 

```
  - image: gcr.io/skippbox/kubectl:v1.3.0
    args:
      - proxy
      - "-p"
      - "8080"
    name: proxy
    imagePullPolicy: Always
```

**Comment by sebgoa** [comment]
This proxy is for the kubewatch controller to talk to the Kubernetes API master.

indeed, it is not intended to bypass your corporate proxy.

**Comment by SydOps** [comment]
@sebgoa 

So how can I pass the http_proxy and https_proxy to the containers/pods?

Added below environments in `kubewatch.yaml`, but doesn't work. 
```
env:
    - name: http_proxy
       value: http://<proxy>:<port>/
    - name: https_proxy
       value: http://<proxy>:<port>/
```
